### ISSUE TITLE
Динамическая память

### ISSUE THREAD

**Issue by David2261** [David2261/Ping_Pong_C#1]
Нужно написать все способы работы с динамической памятью.

1.  Как создать отдельный блок ОЗУ для данного процесса
2.  Как наследовать одномерные, двумерные и трехмерные массивы, как параметры в функцию
3.  Как с помощью указателей изменять массив
4.  Как создать приоритеты для указателей

**Comment by BulatNS31** [comment]
1. Для создания блока для хранения данных ОЗУ используется функция malloc (memory allocate - заполняется различным кэшем и мусором) или calloc (callable allocate - заполняется нулями) из библиотеки stdlib.h
```C
#include <stdlib.h>
 
int main() {
    int *a = (int)malloc(sizeof(int));
    return 0;
}
```

**Comment by BulatNS31** [comment]
2. 
```C
int somefunction(int **arg_1, char ***arg_2);
```
