### ISSUE TITLE
Статическая память

### ISSUE THREAD

**Issue by David2261** [David2261/Ping_Pong_C#2]
Нужно разобраться, как работает статическая память

1.  Как создать массив статических данных и какими они бывают
2.  Как можно управлять статическими данными
3.  Как статический массив передавать, как параметр для функции
4.  Как можно перестраивать статический массив в динамический

**Comment by BulatNS31** [comment]
1. Статический массив - это заранее установленое количество используемой памяти и определенного типа
int A[36] = {0}

**Comment by BulatNS31** [comment]
2. Пример работы со статическим массивом
 ```C
#include <stdio.h>
int main()
{
  int a[5]; // объявлен массив a из 5 элементов
  int i;
  // Ввод элементов массива
  for (i = 0; i<5; i++) 
  {
    printf("a[%d] = ", i);
    scanf("%d", &a[i]); // &a[i] - адрес i-го элемента массива
  }
  // Вывод элементов массива
  for (i = 0; i<5; i++)
    printf("%d ", a[i]); // пробел в формате печати обязателен
  getchar(); getchar();
  return 0;
}
```

**Comment by BulatNS31** [comment]
3. Передача в виде аргумента в функцию
```C
int abc(int A[]):
    ...
```

**Comment by BulatNS31** [comment]
4.  Если только с помощью цикла
```C
int A[3]={0, 2, 3};
int i =0;
int B* = (int)malloc(sizeof(int);
while (i < 3) {
    int B = (int)realloc(*B, sizeof(int)*(*B)+1);
   B[i] = A[i];
   i++;
}

```
